### ISSUE TITLE
Was wird die Lizenz sein?

### ISSUE THREAD

**Issue by cstuder** [MeteoSwiss/publication-opendata#40]
Im Readme ist nur eine unspezifizierte "Open Data license by MeteoSwiss" erwähnt. Gibt es diese bereits oder wird sie noch ausgearbeitet?

**Comment by mchaamsler** [comment]
Danke für die Frage. MeteoSchweiz wird ihre Open Data unter CC-BY verfügbar machen.

**Comment by cstuder** [comment]
Ah, sehr gut. Danke für die Info.

(Und schön zu sehen, dass du involviert bist.) ;-)
